export const FETCH_MILESTONE_REQUEST = "FETCH_MILESTONE_REQUEST";
export const FETCH_MILESTONE_SUCCESS = "FETCH_MILESTONE_SUCCESS";
export const FETCH_MILESTONE_FAILURE = "FETCH_MILESTONE_FAILURE";
export const CHANGE_MASTER = "CHANGE_MASTER";
export const SAVE_COMPLETED_MILESTONE = "SAVE_COMPLETED_MILESTONE";
export const REMOVE_COMPLETED_MILESTONE = "REMOVE_COMPLETED_MILESTONE";
